export default [
  {
    'type': 'Cisco ASR1006',
    'normal': 'asr5500.png',
    'warn': 'asr5500_warn.png',
    'error': 'asr5500_error.png',
  },
  {
    'type': 'Cisco ASR1002-HX',
    'normal': 'asr5500.png',
    'warn': 'asr5500_warn.png',
    'error': 'asr5500_error.png',
  },
  {
    'type': 'Cisco ASR1013',
    'normal': 'asr5500.png',
    'warn': 'asr5500_warn.png',
    'error': 'asr5500_error.png',
  },
  {
    'type': 'Cisco N5K-C5672UP',
    'normal': 'nexus5000.png',
    'warn': 'nexus5000_warn.png',
    'error': 'nexus5000_error.png',
  },
  {
    'type': 'Cisco N5K-C5548',
    'normal': 'nexus5000.png',
    'warn': 'nexus5000_warn.png',
    'error': 'nexus5000_error.png',
  },
  {
    'type': 'Cisco N7K-C7010',
    'normal': 'nexus7000.png',
    'warn': 'nexus7000_warn.png',
    'error': 'nexus7000_error.png',
  },
  {
    'type': 'Cisco N7K-C7706',
    'normal': 'nexus7000.png',
    'warn': 'nexus7000_warn.png',
    'error': 'nexus7000_error.png',
  },
  {
    'type': 'Cisco N7K-C7710',
    'normal': 'nexus7000.png',
    'warn': 'nexus7000_warn.png',
    'error': 'nexus7000_error.png',
  },
  {
    'type': 'Cisco Catalyst 6509',
    'normal': 'layer3.png',
    'warn': 'layer3_warn.png',
    'error': 'layer3_error.png',
  },
  {
    'type': 'Cisco C6807-XL',
    'normal': 'layer3.png',
    'warn': 'layer3_warn.png',
    'error': 'layer3_error.png',
  },
  {
    'type': 'Cisco WS-C6504-E',
    'normal': 'layer3.png',
    'warn': 'layer3_warn.png',
    'error': 'layer3_error.png',
  },
  {
    'type': 'Cisco NCS-5500',
    'normal': 'ncs6000.png',
    'warn': 'ncs6000_warn.png',
    'error': 'ncs6000_error.png',
  },
  {
    'type': 'Cisco 7606-S',
    'normal': 'routes.png',
    'warn': 'routes_warn.png',
    'error': 'routes_error.png',
  },
  {
    'type': 'Cisco ISR-4431',
    'normal': 'route.png',
    'warn': 'route_warn.png',
    'error': 'route_error.png',
  },
  {
    'type': 'Cisco WS-C4948E',
    'normal': 'switch.png',
    'warn': 'switch_warn.png',
    'error': 'switch_error.png',
  },
]